### ISSUE TITLE
More complex model management (multiple models, model reloading etc...)

### ISSUE THREAD

**Issue by bsergean** [Lightning-AI/LitServe#282] opened 2024-09-19 21:32 UTC
## 🚀 Feature

Supporting model reloads (when a new version is available) and multiple models.

### Motivation

Other servers supports this so to be more attractive that would be a nice feature.

### Pitch

Right now it's obvious on how to serve one model, but what if there are multiple ones (and the request (binary, or HTTP arguments) will tell which model should be used).

### Alternatives

Run N instances for the N models present at a certain time, but if a new model appear, that won't work.

### Additional context

We have an internal C++ server that supports this, torch.serve support that too with I believe what they call an orchestrator.

**Comment by bsergean** [comment] 2024-09-20 16:33
Looks like a duplicate of https://github.com/Lightning-AI/LitServe/issues/271

**Comment by aniketmaurya** [comment] 2024-10-07 11:04
closing since duplicate of #271

**Closed by aniketmaurya** 2024-10-07 11:04 UTC
Labels: enhancement, help wanted
